### ISSUE TITLE
Last Stage Phase --> CartoDB <--- Error

### ISSUE THREAD

**Issue by kyroskoh** [jbuonagurio/docker-cartodb#3]
I have encountered an error as shown below, where it is trying to create cartodb from unpackaged:

*\* Execute cartodb:db:setup
rake aborted!
PG::Error: ERROR:  extension "cartodb" has no update path from version "unpackaged" to version "0.8.0"
CONTEXT:  SQL statement "CREATE EXTENSION cartodb VERSION '0.8.0' FROM unpackaged"
PL/pgSQL function inline_code_block line 10 at SQL statement
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in`block in execute_query'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/logging.rb:37:in `log_yield'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in`execute_query'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in`check_disconnect_errors'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in`_execute'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in`check_database_errors'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in`block in synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in`synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:79:in`execute_dui'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:72:in `execute_ddl'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:135:in`run'
/cartodb/app/models/user.rb:2043:in `block (2 levels) in upgrade_cartodb_postgres_extension'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:323:in`_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:285:in `block in transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in`block in synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in`synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:278:in `transaction'
/cartodb/app/models/user.rb:2036:in`block in upgrade_cartodb_postgres_extension'
/cartodb/app/models/user.rb:575:in `in_database'
/cartodb/app/models/user.rb:2035:in`upgrade_cartodb_postgres_extension'
/cartodb/app/models/user.rb:2018:in `load_cartodb_functions'
/cartodb/app/models/user.rb:1517:in`setup_new_user'
/cartodb/app/models/user.rb:1728:in `setup_user'
/cartodb/app/models/user.rb:166:in`after_create'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1585:in `block (2 levels) in _save'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in`around_create'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1578:in `block in _save'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in`around_save'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1573:in `_save'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in`block (2 levels) in save'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `block in checked_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:323:in`_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:285:in `block in transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in`block in synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in`synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/database/query.rb:278:in `transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in`checked_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block in save'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1713:in`checked_save_failure'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `save'
/cartodb/lib/tasks/setup.rake:36:in`block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:205:in`block in execute'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:200:in`execute'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:144:in`invoke'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in`block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in`block in top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:88:in`top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:133:in`standard_exception_handling'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/usr/local/rvm/rubies/ruby-1.9.3-p547/bin/rake:32:in`<main>'
Tasks: TOP => cartodb:db:setup
The command '/bin/sh -c service postgresql start && service redis-server start &&       bash -l -c "cd /cartodb && bash script/create_dev_user" &&      service postgresql stop && service redis-server stop' returned a non-zero code: 1

Do you know how to solve this issue?

**Comment by jbuonagurio** [comment]
This line most likely needs to be changed, removing the --branch option:

https://github.com/jbuonagurio/docker-cartodb/blob/master/Dockerfile#L54
